"""calculations table

Revision ID: afda547cc744
Revises: 
Create Date: 2021-06-04 11:53:33.558435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afda547cc744'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation',
    sa.Column('calcID', sa.Integer(), nullable=False),
    sa.Column('num1', sa.Integer(), nullable=False),
    sa.Column('num2', sa.Integer(), nullable=False),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('calcID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation')
    # ### end Alembic commands ###
